--- assert_exception(exception[, message]) { ... }
--- assert_no_exception(exceptions, ...[, message]) { ... }

