kind=defined
names=error
visibility=public

--- error -> Integer
検証時のエラーコードを返します。

[[m:OpenSSL::X509::StoreContext#verify]] を呼びだし、
証明書チェインの各証明書を検証した
コールバック([[m:OpenSSL::X509::Store#verify_callback=]])が呼び出され、
StoreContext オブジェクトが渡されますが、このメソッドを呼ぶと
直前の証明書検証結果のエラーコードが得られます。

[[m:OpenSSL::X509::StoreContext#verify]] を呼び出したあと、
このメソッドを呼ぶと検証の最終的な検証結果のエラーコードを返します。

エラーコードの整数値は [[c:OpenSSL::X509]] に定数が定義されています。
詳しくは [[ref:c:OpenSSL::X509#verify_error]] を見てください。
検証に成功した場合は [[m:OpenSSL::X509::V_OK]] を返します。

@see [[m:OpenSSL::X509::Store#error]]

