--- self[args, ...]
--- call(args, ...)
--- call(args, ...) { ... }

    UnboundMethod は bind しなければ起動できません。
    常に例外 TypeError が発生します。

        class Foo
          def foo
          end
        end
        Foo.instance_method(:foo).call

        # => -:5:in `call': you cannot call unbound method; bind first (TypeError)

    ruby 1.8 feature: このメソッドはなくなりました。

